#!/bin/sh
set -e
echo Running custom entrypoint
cd /var/www/html/
mkdir -p bootstrap/cache
mkdir -p storage/framework/sessions
mkdir -p storage/framework/views
mkdir -p storage/framework/cache
php artisan key:generate
php artisan migrate --force
echo "Starting server"
exec /usr/local/bin/apache2-foreground